# Generated by Django 4.1 on 2024-06-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cor", models.CharField(max_length=50)),
                ("inicial", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("valor", models.CharField(max_length=100)),
                ("palavras_chave", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("celular_pais", models.CharField(max_length=3)),
                ("celular_ddd", models.CharField(max_length=3)),
                ("celular_numero", models.CharField(max_length=10)),
                ("senha", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Tamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tamanho", models.CharField(max_length=50)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hom.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(blank=True, upload_to="imagens/")),
                ("inicial", models.BooleanField(default=False)),
                (
                    "cor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hom.cor"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hom.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disponibilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_disponivel", models.IntegerField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hom.produto"
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hom.tamanho"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cor",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hom.produto"
            ),
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=50)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hom.produto"
                    ),
                ),
            ],
        ),
    ]
