# Generated by Django 4.1 on 2024-09-19 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perguntas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("email", models.CharField(blank=True, max_length=10)),
                ("celular", models.CharField(blank=True, max_length=15)),
                ("senha", models.CharField(blank=True, max_length=128)),
                ("cliente", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name="Usuario",
            new_name="UsuarioLoja",
        ),
        migrations.CreateModel(
            name="Respostas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resposta", models.TextField()),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hom.perguntas"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hom.usuariopersonal",
                    ),
                ),
            ],
        ),
    ]
