# Generated by Django 4.1 on 2024-09-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hom", "0002_perguntas_usuariopersonal_rename_usuario_usuarioloja_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariopersonal",
            name="email",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
