# Generated by Django 4.1 on 2024-09-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hom", "0004_usuariopersonal_administrador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariopersonal",
            name="senha",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name="respostas",
            unique_together={("usuario", "pergunta")},
        ),
    ]
