# Generated by Django 4.1 on 2024-10-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hom", "0009_alter_produto_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.CharField(max_length=300),
        ),
    ]
