# Generated by Django 4.1 on 2024-10-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hom", "0011_alter_cor_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="cor",
            unique_together={("produto", "cor")},
        ),
    ]
