# Generated by Django 4.1 on 2024-10-10 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hom", "0013_rename_imagem_imagem_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="produto",
        ),
        migrations.AddField(
            model_name="disponibilidade",
            name="cor",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="hom.cor"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="hom.categoria",
            ),
            preserve_default=False,
        ),
    ]
