# Generated by Django 4.1 on 2024-10-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hom", "0015_remove_produto_categoria_categoriaproduto"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="disponibilidade",
            unique_together={("produto", "tamanho", "cor")},
        ),
    ]
