# Generated by Django 4.1 on 2024-11-08 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hom", "0017_pedido_itempedido_favoritos_carrinho"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinho",
            name="cor",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="hom.cor"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrinho",
            name="tamanho",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="hom.tamanho",
            ),
            preserve_default=False,
        ),
    ]
