# Generated by Django 3.2 on 2024-12-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0018_carrinho_cor_carrinho_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='cor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempedido',
            name='descricao',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tamanho',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempedido',
            name='valor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_pgt',
            field=models.DateField(blank=True, default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='quant_itens',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
