# Generated by Django 3.2 on 2024-12-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0019_auto_20241209_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
