# Generated by Django 3.2 on 2024-12-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0020_auto_20241211_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='Pedido',
            new_name='pedido',
        ),
    ]
