# Generated by Django 3.2 on 2024-12-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0021_rename_pedido_itempedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonal',
            name='celular',
        ),
        migrations.AddField(
            model_name='usuariopersonal',
            name='celular_ddd',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopersonal',
            name='celular_numero',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopersonal',
            name='celular_pais',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, default='-', max_length=20)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('principal', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.usuarioloja')),
            ],
        ),
    ]
