# Generated by Django 3.2 on 2024-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0022_auto_20241220_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pdt_imagens/'),
        ),
    ]
