# Generated by Django 3.2 on 2024-12-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0023_itempedido_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='foto',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
