# Generated by Django 3.2 on 2024-12-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0024_alter_itempedido_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
