# Generated by Django 3.2 on 2025-02-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0025_pedido_numero_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Moveis', 'Moveis'), ('Supermercado', 'Supermercado'), ('Construcao', 'Construcao'), ('Magazine', 'Magazine')], max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='fotosCasaRohr/')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCasaRohr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
    ]
