# Generated by Django 3.2 on 2025-02-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0026_fotos_usuariocasarohr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80, unique=True)),
                ('arquivo', models.FileField(upload_to='casaRohr/catalogos/')),
            ],
        ),
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='casaRohr/fotosCasaRohr/'),
        ),
    ]
