# Generated by Django 3.2 on 2025-02-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0027_auto_20250205_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('pt', models.TextField(blank=True, null=True)),
                ('en', models.TextField(blank=True, null=True)),
                ('es', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
