# Generated by Django 3.2 on 2025-02-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0028_translation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalogos',
        ),
        migrations.DeleteModel(
            name='Fotos',
        ),
        migrations.DeleteModel(
            name='UsuarioCasaRohr',
        ),
    ]
