# Generated by Django 3.2 on 2025-03-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0029_auto_20250207_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDiscipulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('celular_numero', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=128)),
                ('administrador', models.BooleanField(default=False)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_do_lider', to='hom.usuariodiscipulado')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntasDiscipulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('discipulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.discipulados')),
            ],
        ),
        migrations.CreateModel(
            name='RespostasDiscipulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.perguntas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.usuariopersonal')),
            ],
            options={
                'unique_together': {('usuario', 'pergunta')},
            },
        ),
    ]
