# Generated by Django 3.2 on 2025-03-31 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0030_discipulados_perguntasdiscipulado_respostasdiscipulado_usuariodiscipulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodiscipulado',
            name='discipulados',
            field=models.ManyToManyField(related_name='lideres', to='hom.Discipulados'),
        ),
        migrations.AddField(
            model_name='usuariodiscipulado',
            name='lideradoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_do_lider', to='hom.usuariodiscipulado'),
        ),
        migrations.AlterField(
            model_name='usuariodiscipulado',
            name='lider',
            field=models.BooleanField(default=False),
        ),
    ]
