# Generated by Django 3.2 on 2025-04-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0031_auto_20250331_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('discipulados', models.ManyToManyField(related_name='discipuladores', to='hom.Discipulados')),
            ],
        ),
        migrations.CreateModel(
            name='Discipulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('nivel', models.IntegerField()),
                ('discipulador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipulos', to='hom.discipulador')),
            ],
        ),
        migrations.CreateModel(
            name='IgrejaParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='hom.igrejaparceira')),
            ],
        ),
        migrations.DeleteModel(
            name='UsuarioDiscipulado',
        ),
    ]
