# Generated by Django 3.2 on 2025-04-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0032_auto_20250401_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipulados',
            name='licao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
