# Generated by Django 3.2 on 2025-04-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0033_discipulados_licao'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipulador',
            name='telefone',
            field=models.CharField(blank=True, max_length=2022, null=True),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='telefone',
            field=models.CharField(blank=True, max_length=2022, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='telefone',
            field=models.CharField(blank=True, max_length=2022, null=True),
        ),
    ]
