# Generated by Django 3.2 on 2025-04-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0035_alter_discipulo_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipulador',
            name='administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipulador',
            name='igreja',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='master', to='hom.igrejaparceira'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
