# Generated by Django 3.2 on 2025-04-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0036_auto_20250404_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipulados',
            name='nivel',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediario', 'Intermediario'), ('Avançado', 'Avançado')], default='Iniciante', max_length=50),
        ),
    ]
