# Generated by Django 3.2 on 2025-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0037_discipulados_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipulados',
            name='licao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
