# Generated by Django 3.2 on 2025-04-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0038_alter_discipulados_licao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostasdiscipulado',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.perguntasdiscipulado'),
        ),
        migrations.AlterField(
            model_name='respostasdiscipulado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.discipulados'),
        ),
    ]
