# Generated by Django 3.2 on 2025-04-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0039_auto_20250408_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipulados',
            name='proximoEstudo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
