# Generated by Django 3.2 on 2025-04-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0040_discipulados_proximoestudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipulados',
            name='foto',
            field=models.ImageField(blank=True, upload_to='discipulado/'),
        ),
    ]
