# Generated by Django 3.2 on 2025-04-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0041_discipulados_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipulador',
            name='discipulador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipulador',
            name='meu_discipulador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipulador_discipulos', to='hom.discipulador'),
        ),
        migrations.AddField(
            model_name='discipulador',
            name='nivel',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediario', 'Intermediario'), ('Avançado', 'Avançado')], default='Iniciante', max_length=50),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='discipulados',
            field=models.ManyToManyField(related_name='discipulo_discipulados', to='hom.Discipulados'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipulo_master', to='hom.igrejaparceira'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='meu_discipulador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipulo_discipulos', to='hom.discipulador'),
        ),
        migrations.AlterField(
            model_name='discipulador',
            name='discipulados',
            field=models.ManyToManyField(related_name='discipulador_discipulados', to='hom.Discipulados'),
        ),
        migrations.AlterField(
            model_name='discipulador',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipulador_master', to='hom.igrejaparceira'),
        ),
        migrations.AlterField(
            model_name='discipulo',
            name='discipulador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discipulo',
            name='nivel',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediario', 'Intermediario'), ('Avançado', 'Avançado')], default='Iniciante', max_length=50),
        ),
    ]
