# Generated by Django 3.2 on 2025-04-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0042_auto_20250422_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscipuladorDiscipulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vinculo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDiscipulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=2022, null=True)),
                ('senha', models.CharField(max_length=128)),
                ('nivel', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediario', 'Intermediario'), ('Avançado', 'Avançado')], max_length=50)),
                ('discipulador', models.BooleanField(default=False)),
                ('administrador', models.BooleanField(default=False)),
                ('discipulados', models.ManyToManyField(related_name='discipuladores', to='hom.Discipulados')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='hom.igrejaparceira')),
            ],
        ),
        migrations.RemoveField(
            model_name='discipulo',
            name='discipulados',
        ),
        migrations.RemoveField(
            model_name='discipulo',
            name='igreja',
        ),
        migrations.RemoveField(
            model_name='discipulo',
            name='meu_discipulador',
        ),
        migrations.DeleteModel(
            name='Discipulador',
        ),
        migrations.DeleteModel(
            name='Discipulo',
        ),
        migrations.AddField(
            model_name='discipuladordiscipulo',
            name='discipulador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipulador_de', to='hom.usuariodiscipulado'),
        ),
        migrations.AddField(
            model_name='discipuladordiscipulo',
            name='discipulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipulo_de', to='hom.usuariodiscipulado'),
        ),
        migrations.AlterUniqueTogether(
            name='discipuladordiscipulo',
            unique_together={('discipulador', 'discipulo')},
        ),
    ]
