# Generated by Django 3.2 on 2025-04-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0043_auto_20250423_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodiscipulado',
            name='discipulados',
        ),
        migrations.AddField(
            model_name='discipuladordiscipulo',
            name='discipulado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='discipulado', to='hom.discipulados'),
            preserve_default=False,
        ),
    ]
