# Generated by Django 3.2 on 2025-04-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0044_auto_20250423_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodiscipulado',
            name='email',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
