# Generated by Django 3.2 on 2025-04-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0045_alter_usuariodiscipulado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipuladordiscipulo',
            name='nome_turma',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
