# Generated by Django 3.2 on 2025-04-23 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0046_discipuladordiscipulo_nome_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoTurmaDiscipulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipulo_de', to='hom.usuariodiscipulado')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaDiscipulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(blank=True, default='1900-01-01')),
                ('data_fim', models.DateField(blank=True, default='1900-01-01')),
                ('discipulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipulado', to='hom.discipulados')),
                ('discipulador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipulador_de', to='hom.usuariodiscipulado')),
            ],
            options={
                'unique_together': {('nome_turma', 'discipulador')},
            },
        ),
        migrations.DeleteModel(
            name='DiscipuladorDiscipulo',
        ),
        migrations.AddField(
            model_name='alunoturmadiscipulado',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.turmadiscipulado'),
        ),
        migrations.AlterUniqueTogether(
            name='alunoturmadiscipulado',
            unique_together={('turma', 'discipulo')},
        ),
    ]
