# Generated by Django 4.1.13 on 2025-04-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hom", "0047_auto_20250423_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="respostasdiscipulado",
            name="turma",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="hom.turmadiscipulado",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="respostasdiscipulado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hom.usuariodiscipulado"
            ),
        ),
    ]
