# Generated by Django 4.1.13 on 2025-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0048_respostasdiscipulado_turma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, unique=True)),
                ('devocional', models.TextField()),
                ('data', models.DateField(blank=True, default='1900-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('lema', models.CharField(max_length=80)),
                ('logo', models.ImageField(blank=True, upload_to='imagens_igreja/')),
                ('endereco', models.CharField(max_length=80)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=80)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('nome_banco', models.CharField(blank=True, max_length=10)),
                ('num_banco', models.CharField(blank=True, max_length=10)),
                ('agencia', models.CharField(blank=True, max_length=50)),
                ('conta_corrente', models.CharField(blank=True, max_length=50)),
                ('chave_pix', models.CharField(blank=True, max_length=50)),
                ('tipo_chave_pix', models.CharField(blank=True, default='CNPJ', max_length=20)),
                ('qr_code_pix', models.ImageField(blank=True, upload_to='imagens_igreja/')),
            ],
        ),
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('numero_membro', models.CharField(blank=True, default='', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pregacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True)),
                ('link', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, default='1900-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSjb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cargo', models.CharField(choices=[('Pastor', 'Pastor'), ('Seminarista', 'Seminarista')], default='', max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='lideranca/')),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=11)),
                ('youtube', models.CharField(blank=True, max_length=80)),
                ('email', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'unique_together': {('nome', 'cargo')},
            },
        ),
    ]
