# Generated by Django 4.1.13 on 2025-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0049_devocional_igreja_membros_pregacao_usuariosjb_pastor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('arquivo', models.FileField(upload_to='downloads/')),
            ],
        ),
    ]
