# Generated by Django 4.1.13 on 2026-02-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0050_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('foto', models.ImageField(blank=True, upload_to='treino/')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTreinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TreinoExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField(auto_now_add=True)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.treino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.usuariotreinos')),
            ],
        ),
        migrations.AddField(
            model_name='treino',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.usuariotreinos'),
        ),
        migrations.AlterUniqueTogether(
            name='treino',
            unique_together={('nome', 'usuario')},
        ),
        migrations.CreateModel(
            name='ExercicioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=50)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.treino')),
            ],
            options={
                'unique_together': {('treino', 'exercicio')},
            },
        ),
        migrations.CreateModel(
            name='ExercicioExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hom.exercicio')),
                ('treino_executado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='hom.treinoexecutado')),
            ],
            options={
                'unique_together': {('treino_executado', 'exercicio')},
            },
        ),
    ]
