# Generated by Django 4.1.13 on 2026-02-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0051_exercicio_treino_usuariotreinos_treinoexecutado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
