# Generated by Django 4.1.13 on 2026-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0052_alter_exercicio_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='data_fim',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treino',
            name='data_inicio',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
