# Generated by Django 4.1.13 on 2026-02-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0053_treino_data_fim_treino_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinoexecutado',
            name='tempo_treino',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
