# Generated by Django 4.1.13 on 2026-02-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0054_treinoexecutado_tempo_treino'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicioexecutado',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
