# Generated by Django 4.1 on 2024-05-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0002_alter_usuario_senha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missionario",
            name="bandeira",
        ),
        migrations.AlterField(
            model_name="missionario",
            name="foto",
            field=models.ImageField(blank=True, upload_to="missionarios_fotos/"),
        ),
    ]
