# Generated by Django 4.1 on 2024-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0005_pregacao_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("data_nascimento", models.DateField()),
                ("sexo", models.CharField(max_length=1)),
                (
                    "sociedade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UCP", "UCP"),
                            ("UPA", "UPA"),
                            ("UMP", "UMP"),
                            ("SAF", "SAF"),
                            ("UPH", "UPH"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
