# Generated by Django 4.1 on 2024-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0006_membros"),
    ]

    operations = [
        migrations.AddField(
            model_name="membros",
            name="status",
            field=models.CharField(blank=True, default="Comungante", max_length=20),
        ),
    ]
