# Generated by Django 4.1 on 2024-09-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0007_membros_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="diretoria",
            name="instagram",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="membros",
            name="status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
