# Generated by Django 4.1 on 2024-09-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0008_diretoria_instagram_alter_membros_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Igreja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("lema", models.CharField(max_length=80)),
                ("logo", models.ImageField(blank=True, upload_to="igreja/")),
                ("endereco", models.CharField(max_length=80)),
                ("instagram", models.CharField(max_length=50)),
                ("youtube", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("nome_banco", models.CharField(max_length=10)),
                ("num_banco", models.CharField(max_length=10)),
                ("agencia", models.CharField(max_length=50)),
                ("conta_corrente", models.CharField(max_length=50)),
                ("chave_pix", models.CharField(max_length=50)),
                ("qr_code_pix", models.ImageField(blank=True, upload_to="igreja/")),
            ],
        ),
    ]
