# Generated by Django 4.1 on 2024-09-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0010_escoladominical_igreja_tipo_chave_pix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lideranca",
            name="data_nascimento",
            field=models.DateField(default="1900-01-01"),
        ),
        migrations.AddField(
            model_name="lideranca",
            name="telefone",
            field=models.CharField(default="", max_length=11),
            preserve_default=False,
        ),
    ]
