# Generated by Django 4.1 on 2024-09-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0011_lideranca_data_nascimento_lideranca_telefone"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lideranca",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lideranca",
            name="ano_fim",
            field=models.CharField(default="2028", max_length=4),
        ),
        migrations.AddField(
            model_name="lideranca",
            name="ano_inicio",
            field=models.CharField(default="2024", max_length=4),
        ),
        migrations.AddField(
            model_name="programacao",
            name="data",
            field=models.DateField(default="1900-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="igreja",
            name="logo",
            field=models.ImageField(blank=True, upload_to="imagens_igreja/"),
        ),
        migrations.AlterField(
            model_name="igreja",
            name="qr_code_pix",
            field=models.ImageField(blank=True, upload_to="imagens_igreja/"),
        ),
        migrations.AlterField(
            model_name="lideranca",
            name="cargo",
            field=models.CharField(
                choices=[("Diacono", "Diacono"), ("Presbitero", "Presbitero")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lideranca",
            unique_together={("nome", "cargo", "ano_inicio")},
        ),
        migrations.CreateModel(
            name="Pastor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "cargo",
                    models.CharField(
                        choices=[("Pastor", "Pastor"), ("Seminarista", "Seminarista")],
                        default="",
                        max_length=50,
                    ),
                ),
                ("foto", models.ImageField(blank=True, upload_to="lideranca/")),
                ("data_nascimento", models.DateField()),
                ("telefone", models.CharField(max_length=11)),
                ("youtube", models.CharField(max_length=80)),
                ("email", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("nome", "cargo")},
            },
        ),
        migrations.RemoveField(
            model_name="lideranca",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="lideranca",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="lideranca",
            name="telefone",
        ),
    ]
