# Generated by Django 4.1 on 2024-09-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0012_alter_lideranca_unique_together_lideranca_ano_fim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastor",
            name="email",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="pastor",
            name="telefone",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name="pastor",
            name="youtube",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
