# Generated by Django 4.1 on 2024-09-14 18:51

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0013_alter_pastor_email_alter_pastor_telefone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membros",
            name="numero",
            field=models.CharField(default='', max_length=5),
        ),
    ]
