# Generated by Django 4.1 on 2024-09-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0014_membros_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membros",
            name="numero",
            field=models.CharField(default="", max_length=5),
        ),
    ]
