# Generated by Django 4.1 on 2024-09-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0015_alter_membros_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="membros",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="membros",
            name="observacoes",
            field=models.CharField(default="", max_length=200),
        ),
    ]
