# Generated by Django 4.1 on 2024-09-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0016_membros_ativo_membros_observacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membros",
            name="nome",
            field=models.CharField(max_length=50),
        ),
    ]
