# Generated by Django 4.1 on 2024-09-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0017_alter_membros_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diretoria",
            name="instagram",
        ),
        migrations.CreateModel(
            name="RedesSociais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responsavel", models.CharField(max_length=50)),
                (
                    "rede_social",
                    models.CharField(
                        choices=[
                            ("Instagram", "Instagram"),
                            ("Facebook", "Facebook"),
                            ("Whatsapp", "Whatsapp"),
                            ("Youtube", "Youtube"),
                        ],
                        max_length=50,
                    ),
                ),
                ("link", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("responsavel", "rede_social", "link")},
            },
        ),
    ]
