# Generated by Django 4.1 on 2024-10-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rl", "0018_remove_diretoria_instagram_redessociais"),
    ]

    operations = [
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("arquivo", models.FileField(upload_to="downloads/")),
            ],
        ),
        migrations.AddField(
            model_name="diretoria",
            name="conselheiro",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
