# Generated by Django 4.1 on 2024-11-14 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0019_download_diretoria_conselheiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='fotos/')),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
                ('ministerio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rl.ministerio')),
            ],
        ),
        migrations.AddField(
            model_name='programacao',
            name='nome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programacao',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='FotosMinisterios',
        ),
        migrations.AddField(
            model_name='fotos',
            name='programacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rl.programacao'),
        ),
    ]
