# Generated by Django 4.1 on 2024-11-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0020_fotos_programacao_nome_alter_programacao_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
