# Generated by Django 3.2 on 2024-11-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0021_alter_programacao_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversariantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
            ],
            options={
                'db_table': 'vw_aniversariantes',
                'managed': False,
            },
        ),
    ]
