# Generated by Django 3.2 on 2024-11-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0022_aniversariantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='observacoes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
