# Generated by Django 3.2 on 2024-12-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0023_alter_membros_observacoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aniversariantes',
        ),
    ]
