# Generated by Django 3.2 on 2025-02-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0025_auto_20250108_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministerio',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ministerio',
            unique_together={('nome', 'ano')},
        ),
    ]
