# Generated by Django 3.2 on 2025-02-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0026_auto_20250202_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='alfabetizado',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='membros',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='membros',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='membros',
            name='estado_civil',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='membros',
            name='mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_da_mae', to='rl.membros'),
        ),
        migrations.AddField(
            model_name='membros',
            name='nacionalidade',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='membros',
            name='naturalidade',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='membros',
            name='ocupacao',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='membros',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_do_pai', to='rl.membros'),
        ),
        migrations.AddField(
            model_name='membros',
            name='religiao_conjuge',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='membros',
            name='rua',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='membros',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='membros',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
