# Generated by Django 3.2 on 2025-02-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0027_auto_20250219_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='mae_nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membros',
            name='pai_nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membros',
            name='alfabetizado',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='membros',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='membros',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='membros',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIÚVO', 'Viúvo(a)'), ('SEPARADO', 'Separado(a)'), ('UNIÃO ESTÁVEL', 'União Estável')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='membros',
            name='nacionalidade',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='membros',
            name='naturalidade',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='membros',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='membros',
            name='observacoes',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='membros',
            name='ocupacao',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='membros',
            name='religiao_conjuge',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='membros',
            name='rua',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='membros',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
