# Generated by Django 3.2 on 2025-02-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0028_auto_20250219_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='numero_membro',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
