# Generated by Django 3.2 on 2025-02-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0029_membros_numero_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='conjuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjuge_de', to='rl.membros'),
        ),
        migrations.AddField(
            model_name='membros',
            name='conjuge_nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membros',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='membros',
            name='identidade',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
