# Generated by Django 3.2 on 2025-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0030_auto_20250219_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='identidade',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
