# Generated by Django 3.2 on 2025-02-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0031_alter_membros_identidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='alfabetizado',
            field=models.BooleanField(default=True),
        ),
    ]
