# Generated by Django 4.1.13 on 2025-05-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ch", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fotos",
        ),
    ]
