# Generated by Django 4.1.13 on 2025-05-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ch", "0002_delete_fotos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=50)),
                ("texto", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, upload_to="casaRohr/fotosCasaRohr/"),
                ),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categoria_de",
                        to="ch.categorias",
                    ),
                ),
            ],
        ),
    ]
