"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from decouple import config
from pathlib import Path
import os
import pymysql

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
    'rest_framework',
    'bootstrap4',
    'tb',
    'rl',
    'hom',
    'ch',
    # 'proacos',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "django.middleware.csrf.CsrfViewMiddleware",
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "setup.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "setup.wsgi.application"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination'
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "ajdeve95_ajdevelopments",
        "USER": "ajdeve95_anaJulia",
        "PASSWORD": "ajdeve95_anaJulia",
        "HOST": "ajdevelopments.com.br",
        "PORT": "3306",
        "OPTIONS": {
            "charset":"utf8mb4",
            "init_command":"SET sql_mode='STRICT_TRANS_TABLES'"
        }
    },
    "db_ipbregiaoleste": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "ajdeve95_ipbregiaoleste",
        "USER": "ajdeve95_anaJulia",
        "PASSWORD": "ajdeve95_anaJulia",
        "HOST": "ajdevelopments.com.br",
        "PORT": "3306",
        "OPTIONS": {
            "charset":"utf8mb4",
            "init_command":"SET sql_mode='STRICT_TRANS_TABLES'"
        }
    },
    "db_homol": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "ajdeve95_homol",
        "USER": "ajdeve95_anaJulia",
        "PASSWORD": "ajdeve95_anaJulia",
        "HOST": "ajdevelopments.com.br",
        "PORT": "3306",
        "OPTIONS": {
            "charset":"utf8mb4",
            "init_command":"SET sql_mode='STRICT_TRANS_TABLES'"
        }
   },
    "db_casarohr": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "ajdeve95_casarohr",
        "USER": "ajdeve95_anaJulia",
        "PASSWORD": "ajdeve95_anaJulia",
        "HOST": "ajdevelopments.com.br",
        "PORT": "3306",
        "OPTIONS": {
            "charset":"utf8mb4",
            "init_command":"SET sql_mode='STRICT_TRANS_TABLES'"
        }
   }
    #  'db_proacos': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'postgres',
    #     'USER': 'postgres.kljewoxqebzctcfdhedi',
    #     'PASSWORD': 'anaju88339439',
    #     'HOST': 'aws-0-sa-east-1.pooler.supabase.com',
    #     'PORT': '6543',
    # }
}

DATABASE_ROUTERS = ['setup.routers.DatabaseRouter']

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

CORS_ALLOW_CREDENTIALS = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'ajdevelopments.com.br',
    'ipbregiaoleste.com.br',
    'loja.ajdevelopments.com.br',
    'homol.ajdevelopments.com.br',
    'personal.ajdevelopments.com.br',
    'hml.ajdevelopments.com.br',
    'homologacao.ajdevelopments.com.br',
    'igreja.ajdevelopments.com.br',
    'casarohr.com.br',
    'amor.ajdevelopments.com.br'
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "http://ajdevelopments.com.br",
    "https://ajdevelopments.com.br",
    "http://ipbregiaoleste.com.br",
    "https://ipbregiaoleste.com.br",
    'http://loja.ajdevelopments.com.br',
    'https://loja.ajdevelopments.com.br',
    'http://homol.ajdevelopments.com.br',
    'https://homol.ajdevelopments.com.br',
    'http://personal.ajdevelopments.com.br',
    'https://personal.ajdevelopments.com.br',
    'http://hml.ajdevelopments.com.br',
    'https://hml.ajdevelopments.com.br',
    'http://homologacao.ajdevelopments.com.br',
    'https://homologacao.ajdevelopments.com.br',
    'http://amor.ajdevelopments.com.br',
    'https://amor.ajdevelopments.com.br',
    'http://igreja.ajdevelopments.com.br',
    'https://igreja.ajdevelopments.com.br',
    'http://casarohr.com.br',
    'https://casarohr.com.br'
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:4200',
    "http://127.0.0.1:4200",
    'http://ajdevelopments.com.br',
    'https://ajdevelopments.com.br',
    'http://ipbregiaoleste.com.br',
    'https://ipbregiaoleste.com.br',
    'http://loja.ajdevelopments.com.br',
    'https://loja.ajdevelopments.com.br',
    'http://homol.ajdevelopments.com.br',
    'https://homol.ajdevelopments.com.br',
    'http://personal.ajdevelopments.com.br',
    'https://personal.ajdevelopments.com.br',
    'http://hml.ajdevelopments.com.br',
    'https://hml.ajdevelopments.com.br',
    'http://amor.ajdevelopments.com.br',
    'https://amor.ajdevelopments.com.br',
    'http://homologacao.ajdevelopments.com.br',
    'https://homologacao.ajdevelopments.com.br',
    'http://igreja.ajdevelopments.com.br',
    'https://igreja.ajdevelopments.com.br',
    'http://casarohr.com.br',
    'https://casarohr.com.br'
]

X_FRAME_OPTIONS = 'ALLOW-FROM https://anajulia.pythonanywhere.com'

CSRF_COOKIE_HTTPONLY = False   # precisa ser False, senão JS não lê
CSRF_COOKIE_SAMESITE = None  # se estiver em domínios diferentes

SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = True



# DEFAULT_FROM_EMAIL = 'anajulia99@gmail.com'
# EMAIL_BACKEND = config('EMAIL_BACKEND')
# EMAIL_HOST = config('EMAIL_HOST')
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
# EMAIL_PORT = config('EMAIL_PORT')
# EMAIL_USE_SSL = config('EMAIL_USE_SSL')                  # deixe False se usar TLS
# EMAIL_USE_TLS = False

host = "smtp.titan.email"
port = 465
email_remetente = "contato@casarohr.com.br"
email_destinatario = "contato@casarohr.com.br"
senha = "Expresso514#"