# Generated by Django 4.1 on 2024-04-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("data_nascimento", models.DateField(default="1900-01-01")),
                ("telefone", models.CharField(max_length=11)),
                ("telefone_retorno", models.BooleanField(default=False)),
                ("email", models.CharField(max_length=50)),
                ("email_retorno", models.BooleanField(default=False)),
                ("mensagem", models.CharField(default="", max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Pensamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.CharField(max_length=50)),
                ("autoria", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
            ],
        ),
    ]
