# Generated by Django 4.1 on 2024-05-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("link", models.CharField(max_length=50)),
                ("foto", models.ImageField(blank=True, upload_to="clientes/")),
                ("data_inicio", models.DateField(blank=True, default="1900-01-01")),
                ("data_prevista", models.DateField(blank=True, default="1900-01-01")),
                ("data_fim", models.DateField(blank=True, default="1900-01-01")),
                ("valorDominio", models.CharField(blank=True, max_length=10)),
                ("valorSite", models.CharField(blank=True, max_length=10)),
                ("valorMensal", models.CharField(blank=True, max_length=10)),
                ("observacoes", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Pensamento",
        ),
    ]
