# Generated by Django 4.1 on 2024-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0002_cliente_delete_pensamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/clientes/"),
        ),
    ]
