# Generated by Django 4.1 on 2024-05-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0004_cliente_foto_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="foto_mobile",
        ),
    ]
