# Generated by Django 4.1 on 2024-05-29 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0006_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("valor_pgt", models.CharField(max_length=100, unique=True)),
                ("data_pgt", models.DateField(blank=True)),
                ("numero_pgt", models.CharField(max_length=3)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tb.usuario"
                    ),
                ),
            ],
        ),
    ]
