# Generated by Django 4.1 on 2024-05-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0007_alter_usuario_cpf_alter_usuario_email_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="data_pgt",
            field=models.DateField(blank=True, default="1900-01-01"),
        ),
    ]
