# Generated by Django 4.1 on 2024-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0008_alter_pedido_data_pgt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="valor_pgt",
            field=models.CharField(max_length=100),
        ),
    ]
