# Generated by Django 4.1 on 2024-05-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0009_alter_pedido_valor_pgt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=30)),
                ("numero", models.CharField(max_length=10)),
                ("complemento", models.CharField(max_length=20)),
                ("bairro", models.CharField(max_length=30)),
                ("cidade", models.CharField(max_length=30)),
                ("estado", models.CharField(max_length=20)),
                ("pais", models.CharField(max_length=20)),
                ("cep", models.CharField(max_length=10)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tb.usuario"
                    ),
                ),
            ],
        ),
    ]
