# Generated by Django 4.1 on 2024-05-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0010_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="complemento",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
