# Generated by Django 4.1 on 2024-06-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0012_endereco_principal"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="link_pgt",
            field=models.CharField(default="", max_length=100),
        ),
    ]
