# Generated by Django 4.1 on 2024-06-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0013_pedido_link_pgt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="complemento",
            field=models.CharField(blank=True, default="-", max_length=20),
        ),
    ]
