# Generated by Django 4.1 on 2024-06-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0014_alter_endereco_complemento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="item",
            new_name="itens",
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("valor_pdt", models.CharField(max_length=100)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tb.usuario"
                    ),
                ),
            ],
        ),
    ]
