# Generated by Django 4.1 on 2024-06-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0015_rename_item_pedido_itens_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="numero_pgt",
        ),
        migrations.AddField(
            model_name="item",
            name="numero_pgt",
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
