# Generated by Django 3.2 on 2025-04-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0019_auto_20250415_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemdemanda',
            name='anexos',
            field=models.FileField(blank=True, null=True, upload_to='demandas/'),
        ),
        migrations.AlterField(
            model_name='mensagemdemanda',
            name='autor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb.usuario'),
        ),
    ]
