# Generated by Django 4.1.13 on 2025-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0020_auto_20250415_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosAmor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='fotosAmor/')),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
                ('capa', models.BooleanField(default=True)),
            ],
        ),
    ]
