# Generated by Django 4.1.13 on 2025-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0021_fotosamor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotosamor',
            name='data',
            field=models.DateField(blank=True, default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='fotosamor',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
