# Generated by Django 4.1.13 on 2026-01-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0022_fotosamor_data_alter_fotosamor_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPresentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(choices=[('cozinha', 'Cozinha'), ('sala', 'Sala'), ('quarto', 'Quarto'), ('outros', 'Outros'), ('roupa', 'Roupas')], max_length=10)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, default='1900-01-01')),
            ],
        ),
    ]
